/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.outsourcingcompany.view;

import com.outsourcingcompany.database.OracleConn;
import com.outsourcingcompany.model.*;
import com.outsourcingcompany.controller.Controller;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Achmad Muchlasin
 */
public class ProjectView extends javax.swing.JFrame {

    Controller assignment;

    /**
     * Creates new form ProjectView
     */
    public ProjectView() throws SQLException {
        initComponents();
        this.assignment = new Controller();
        this.showComboBoxEmployee();
        this.showComboBoxJob();
        this.showTableJob();
        this.showTableProject();
        this.showTableEmployee();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblOnProgressProject = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOnProgressProject = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbOutstandingJob = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnDel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEmployeeList = new javax.swing.JTable();
        lblEmployeeList = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDueDate = new javax.swing.JTextField();
        cbJobId = new javax.swing.JComboBox<>();
        cbEmpId = new javax.swing.JComboBox<>();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblTitle.setText("OUTSOURCING COMPANY APP");

        lblOnProgressProject.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        lblOnProgressProject.setText("On Progress Project");

        jLabel2.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel2.setText("Job ID");

        jLabel3.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel3.setText("Employee ID");

        tbOnProgressProject.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        tbOnProgressProject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbOnProgressProject);

        jLabel4.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel4.setText("Start Date");

        tbOutstandingJob.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        tbOutstandingJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbOutstandingJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbOutstandingJobMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbOutstandingJob);

        btnAdd.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel6.setText("Outstanding Job");

        btnDel.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        tblEmployeeList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmployeeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblEmployeeList);

        lblEmployeeList.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        lblEmployeeList.setText("Employee List");

        jLabel5.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jLabel5.setText("Due Date");

        cbJobId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbEmpId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)
                                        .addComponent(txtStartDate)
                                        .addComponent(jLabel5)
                                        .addComponent(txtDueDate)
                                        .addComponent(cbJobId, 0, 123, Short.MAX_VALUE)
                                        .addComponent(cbEmpId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblOnProgressProject)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployeeList)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeList)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblOnProgressProject))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbJobId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Project project = new Project();
        try {
            project.setJob(this.assignment.getJobData().get(this.cbJobId.getSelectedIndex()));
            project.setEmployee(this.assignment.getEmployeeData().get(this.cbEmpId.getSelectedIndex()));
            project.setStartDate(new SimpleDateFormat("dd/MM/yyyy").parse(this.txtStartDate.getText()));
            project.setDueDate(new SimpleDateFormat("dd/MM/yyyy").parse(this.txtDueDate.getText()));
            this.assignment.insertProject(project);
            
            JOptionPane.showMessageDialog(null, "Project added!");
            this.showTableProject();
            
        } catch (SQLException | ParseException err) {
            System.out.println(err);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void tblEmployeeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeListMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblEmployeeListMouseClicked

    private void tbOutstandingJobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbOutstandingJobMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tbOutstandingJobMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            String selectedRow = this.tbOnProgressProject.getValueAt(this.tbOnProgressProject.getSelectedRow(), 0).toString();
            Project project = new Project();
            project.setPrjId(Integer.parseInt(selectedRow));
            project.setJob(this.assignment.getJobData().get(this.cbJobId.getSelectedIndex()));
            project.setEmployee(this.assignment.getEmployeeData().get(this.cbEmpId.getSelectedIndex()));
            project.setStartDate(new SimpleDateFormat("dd/MM/yyyy").parse(this.txtStartDate.getText()));
            project.setDueDate(new SimpleDateFormat("dd/MM/yyyy").parse(this.txtDueDate.getText()));
            this.assignment.updateProject(project);
            
            JOptionPane.showMessageDialog(null, "Project updated!");
            this.showTableProject();
            
        } catch (SQLException | ParseException err) {
            System.out.println(err);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        try {
            String selected = this.tbOnProgressProject.getValueAt(this.tbOnProgressProject.getSelectedRow(), 0).toString();
            this.assignment.deleteProject(Integer.parseInt(selected));
            
            JOptionPane.showMessageDialog(null, "Project deleted!");
            this.showTableProject();
        } catch (NumberFormatException | SQLException e) {
            Logger.getLogger(ProjectView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int ans = JOptionPane.showOptionDialog(this,
            "Do you want to logout?",
            "Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (ans == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "You have been logged out!");
            try {
                new LoginView().show();
                setVisible(false);

            } catch (SQLException ex) {
                Logger.getLogger(HomeAdminView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProjectView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ProjectView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbEmpId;
    private javax.swing.JComboBox<String> cbJobId;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEmployeeList;
    private javax.swing.JLabel lblOnProgressProject;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tbOnProgressProject;
    private javax.swing.JTable tbOutstandingJob;
    private javax.swing.JTable tblEmployeeList;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables

    private void showComboBoxEmployee() throws SQLException {
        DefaultComboBoxModel dtmEmployee = new DefaultComboBoxModel();
        for (Employee emp : this.assignment.getEmployeeData()) {
            dtmEmployee.addElement(emp.getEmpId());
        }

        this.cbEmpId.setModel(dtmEmployee);
    }

    private void showComboBoxJob() throws SQLException {
        DefaultComboBoxModel dtmJob = new DefaultComboBoxModel();
        for (Job j : this.assignment.getJobData()) {
            dtmJob.addElement(j.getJobId());
        }

        this.cbJobId.setModel(dtmJob);

    }

    private void showTableJob() throws SQLException {
        DefaultTableModel dtmJobList = new DefaultTableModel(new String[]{"JOB ID", "JOB NAME", "DESCRIPTION", "CLIENT NAME"}, 0);
        dtmJobList.setRowCount(0);
        for (Job j : this.assignment.getJobClientData()) {
            dtmJobList.addRow(new String[]{j.getJobId().toString(), j.getJobName(), j.getJobDesc(), j.getClient().getClName()});
        }

        tbOutstandingJob.setModel(dtmJobList);
    }

    private void showTableProject() throws SQLException {
        DefaultTableModel dtmProjectList = new DefaultTableModel(new String[]{"PROJECT ID", "JOB NAME", "EMPLOYEE NAME", "START DATE", "DUE DATE"}, 0);
        dtmProjectList.setRowCount(0);
        for (Project p : this.assignment.getProjectData()) {
            dtmProjectList.addRow(new String[]{p.getPrjId().toString(), p.getJob().getJobName(), p.getEmployee().getEmpName(), p.getStartDate().toString(), p.getDueDate().toString()});
        }

        tbOnProgressProject.setModel(dtmProjectList);
    }

    private void showTableEmployee() throws SQLException {
        DefaultTableModel dtmEmpList = new DefaultTableModel(new String[]{"EMPLOYEE ID", "NAME", "ADDRESS", "GENDER", "PHONE NO", "EMAIL"}, 0);
        dtmEmpList.setRowCount(0);
        for (Employee e : this.assignment.getEmployeeData()) {
            dtmEmpList.addRow(new String[]{e.getEmpId().toString(), e.getEmpName(), e.getEmpAddr(), e.getEmpGender(), e.getEmpPhoneNo(), e.getEmpEmail()});

        }

        tblEmployeeList.setModel(dtmEmpList);
    }

}
